version: "3.8"

services:
  cpp:
    image: ntuangiang/mongo-cpp # Image latest
    ports:
      - 2202:22 # Remote
      - 7777:7777 # Debug
    restart: always

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
      - 8081:8081
    restart: always